global:
  scrape_interval: 15s

scrape_configs:
- job_name: garnet-op-node
  static_configs:
  - targets: ['opstack-garnet-op-node:7300']
- job_name: ethereum-erigon
  metrics_path: /debug/metrics/prometheus
  static_configs:
  - targets: ['erigon-ethereum-holesky:6060']
- job_name: host-node
  static_configs:
  - targets: ['host.containers.internal:9100']
- job_name: reverse-proxy
  static_configs:
  - targets: ['reverse-proxy:8080']