global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['opstack-garnet-op-node:7300', 'erigon-ethereum-holesky:6060/debug/metrics/prometheus', 'host.containers.internal:9100']