tasks:
  rebuild:molasses:
    command: nixos-rebuild -I nixos-config=/home/richardsl/nixos/src/molasses-wsl/configuration.nix switch
  rebuild:brix0001:
    command: nixos-rebuild -I nixos-config=/home/richardsl/nixos/src/brix0001/configuration.nix switch

  restart:whoami:
    command: systemctl restart podman-whoami.service
  restart:reverse-proxy:
    command: systemctl restart podman-reverse-proxy.service
  restart:holesky-node:
    command: systemctl restart podman-erigon-ethereum-holesky.service

  watch:reverse-proxy:
    command: journalctl -u podman-reverse-proxy.service -f

pipelines:
  run:molasses:
    - task: rebuild:molasses
    - task: restart:whoami
      depends_on: rebuild:molasses
    - task: restart:reverse-proxy
      depends_on: rebuild:molasses
    # - task: restart:holesky-node
    #   depends_on: rebuild:molasses
  run:brix0001:
    - task: rebuild:brix0001
    - task: restart:whoami
      depends_on: rebuild:brix0001
    - task: restart:reverse-proxy
      depends_on: rebuild:brix0001
    - task: restart:holesky-node
      depends_on: rebuild:brix0001

watchers:
  watch:molasses:
    watch: [ "src/common/*.nix", "src/common/etc/**", "src/molasses-wsl/*.nix", "src/secrets/*.nix" ]
    events: [ "create", "write", "remove", "rename" ]
    task: rebuild:molasses