[api]
  dashboard = true
  insecure = false

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[providers.file]
  filename = "/etc/traefik/dynamic.toml"
  watch = true

[entryPoints.web]
  address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

[entryPoints.websecure]
  address = ":443"

[entryPoints.erigongrpc]
  address = ":9090"

[entryPoints.erigonsnaptcp]
  address = ":42069"
[entryPoints.erigonsnapudp]
  address = ":42069/udp"

[entryPoints.erigoneth68peeringtcp]
  address = ":30303"
[entryPoints.erigoneth68peeringudp]
  address = ":30303/udp"

[entryPoints.erigoneth67peeringtcp]
  address = ":30304"
[entryPoints.erigoneth67peeringudp]
  address = ":30304/udp"

[entryPoints.erigongrpcin]
  address = ":9091"

[entryPoints.erigonsentineludp]
  address = ":4000"
[entryPoints.erigonsentineltcp]
  address = ":4001"